// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.techvalleyhigh.frc5881;

import edu.wpi.first.wpilibj.ADXRS450_Gyro;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SPI;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.Victor;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController armSpinnerSpeedController;
    public static DigitalInput armArmUpperLimitSwitch;
    public static DigitalInput armArmLowerLimitSwitch;
    public static SpeedController armArmSpeedController;
    public static Ultrasonic armUltrasonicBallSensor;
    public static DigitalInput armBallCaptureLimitSwitch;
    public static SpeedController driveControlLeftSpeedController1;
    public static SpeedController driveControlLeftSpeedController2;
    public static SpeedController driveControlRightSpeedController1;
    public static SpeedController driveControlRightSpeedController2;
    public static RobotDrive driveControlRobotDrive;
    public static PowerDistributionPanel chassisPowerDistributionPanel;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static ADXRS450_Gyro driveControlDigitalGyro;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        armSpinnerSpeedController = new Talon(4);
        LiveWindow.addActuator("Arm", "Spinner Speed Controller", (Talon) armSpinnerSpeedController);
        
        armArmUpperLimitSwitch = new DigitalInput(2);
        LiveWindow.addSensor("Arm", "Arm Upper Limit Switch", armArmUpperLimitSwitch);
        
        armArmLowerLimitSwitch = new DigitalInput(3);
        LiveWindow.addSensor("Arm", "Arm Lower Limit Switch", armArmLowerLimitSwitch);
        
        armArmSpeedController = new Talon(5);
        LiveWindow.addActuator("Arm", "Arm Speed Controller", (Talon) armArmSpeedController);
        
        armUltrasonicBallSensor = new Ultrasonic(0, 1);
        LiveWindow.addSensor("Arm", "Ultrasonic Ball Sensor", armUltrasonicBallSensor);
        
        armBallCaptureLimitSwitch = new DigitalInput(4);
        LiveWindow.addSensor("Arm", "Ball Capture Limit Switch", armBallCaptureLimitSwitch);
        
        driveControlLeftSpeedController1 = new Victor(0);
        LiveWindow.addActuator("Drive Control", "Left Speed Controller 1", (Victor) driveControlLeftSpeedController1);
        
        driveControlLeftSpeedController2 = new Victor(1);
        LiveWindow.addActuator("Drive Control", "Left Speed Controller 2", (Victor) driveControlLeftSpeedController2);
        
        driveControlRightSpeedController1 = new Victor(2);
        LiveWindow.addActuator("Drive Control", "Right Speed Controller 1", (Victor) driveControlRightSpeedController1);
        
        driveControlRightSpeedController2 = new Victor(3);
        LiveWindow.addActuator("Drive Control", "Right Speed Controller 2", (Victor) driveControlRightSpeedController2);
        
        driveControlRobotDrive = new RobotDrive(driveControlLeftSpeedController1, driveControlLeftSpeedController2,
              driveControlRightSpeedController1, driveControlRightSpeedController2);
        
        driveControlRobotDrive.setSafetyEnabled(true);
        driveControlRobotDrive.setExpiration(0.1);
        driveControlRobotDrive.setSensitivity(0.5);
        driveControlRobotDrive.setMaxOutput(1.0);

        chassisPowerDistributionPanel = new PowerDistributionPanel(0);
        LiveWindow.addSensor("Chassis", "PowerDistributionPanel", chassisPowerDistributionPanel);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        driveControlDigitalGyro = new ADXRS450_Gyro(SPI.Port.kOnboardCS0);
        LiveWindow.addSensor("Drive Control", "DigitalGyro", driveControlDigitalGyro);
    }
}
