// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.techvalleyhigh.frc5881.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.techvalleyhigh.frc5881.Robot;
import org.techvalleyhigh.frc5881.util.ClockTimer;

/**
 *
 */
public class AssistedDrive extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private double m_distanceInFeet;
    private double m_relativeBearing;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    
    private double absBearing;
    private int gyroTolerance;
    private double totalDriveTimeNeeded;
    private float drivePower;
    private ClockTimer timer;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AssistedDrive(double distanceInFeet, double relativeBearing) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_distanceInFeet = distanceInFeet;
        m_relativeBearing = relativeBearing;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveControl);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	absBearing = Robot.driveControl.getGyroAngle() + m_relativeBearing;
    	gyroTolerance = Robot.driveControl.getAutoGyroTolerance();
    	setTravelTime();
    	drivePower = Robot.driveControl.getAutoSpeedValue();
    	System.out.println("Assisted Drive Leg - " + m_distanceInFeet + "ft == "
    			+ totalDriveTimeNeeded + "sec at power " + drivePower
    			+ " bearing " + m_relativeBearing + " rel deg " + absBearing
    			+ " abs deg +-" + gyroTolerance);
    	timer = new ClockTimer(totalDriveTimeNeeded);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if (!isAngleInTolerance()) {
    		// If bearing off... stop timer and turn robot...

    		timer.stop();

    		double degreeOffset = degreeOffsetToMatchBearing();

    		float direction = 1;
    		if (Math.abs(degreeOffset) != degreeOffset) {
    			direction = -1;
    		}

    		float speed = .6f;
    		if (Math.abs(degreeOffset) > 90) {
    			speed = .6f;
    		} else if (Math.abs(degreeOffset) > 45) {
    			speed = .4f;
    		} else {
    			speed = .3f;
    		}

    		System.out.println("[TURN] Offset " + degreeOffset + " Drive(0, "
    				+ direction * speed + ")");

    		Robot.driveControl.rawDrive(0f, direction * speed);
    	} else {
    		// If on bearing, start timer and drive bot...
    		timer.start();

    		Robot.driveControl.rawDrive(drivePower, 0f);
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return timer.isExpired();
    }

    // Called once after isFinished returns true
    protected void end() {
    	timer.stop();
    	Robot.driveControl.stopDrive();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
    
    /**
     * Tests to see if the current gyro angle is within the tolerances specified in the dashboard
     */
    private boolean isAngleInTolerance() {
    	double currentAngle = Robot.driveControl.getGyroAngle();
    	if (absBearing >= currentAngle - gyroTolerance && absBearing <= currentAngle + gyroTolerance) {
    		return true;
    	} else {
    		return false;
    	}
    }

    /**
     * Should return degrees to turn to match the desired bearing. Positive == clockwise.
     */
    private double degreeOffsetToMatchBearing() {
    	double currentAngle = Robot.driveControl.getGyroAngle();
    	return absBearing - currentAngle;
    }

    private void setTravelTime() {
    	double tenFootTravelTime = Robot.driveControl.getAutoSetPowerTime();
    	totalDriveTimeNeeded = (tenFootTravelTime/10) * m_distanceInFeet;
    }
}
